[build-system]
requires = ['poetry-core']
build-backend = 'poetry.core.masonry.api'

[tool.poetry]
name = 'rlai'
version = '1.1.0.dev0'
description = 'Reinforcement Learning:  An Introduction'
readme = 'README.md'
authors = [
    'Matthew Gerber <gerber.matthew@gmail.com>'
]
packages = [
    { include = 'rlai', from = 'src'}
]
repository = 'https://github.com/MatthewGerber/rlai'

[tool.poetry.dependencies]
python = '>=3.10'
scipy = '~=1.11'
matplotlib = '~=3.8'
numpy = '~=1.26'
gymnasium = { version = '~=0.29', extras = ['classic-control', 'box2d', 'mujoco'] }

# the preceding mujoco dependency will install a recent mujoco version just fine. however, the gym/mujoco
# integration is broken for Swimmer-v4 and perhaps other environments. this is unfortunate, since the preceding
# installation for mujoco is much more convenient than the previous approach. if you want to use Swimmer-v4 instead,
# then downgrade mujoco with the following dependency:
mujoco = '<3'

# if you do this, then you will also need to do the following before installing:
#   1. download mujoco 2.3.7:  https://github.com/google-deepmind/mujoco/releases/tag/2.3.7
#   2. move the MuJoCo app to local disk.
#   2. set the following environment variables prior to installing the present package:
#        export MUJOCO_PATH="/path/to/MuJoCo.app"
#        export MUJOCO_PLUGIN_PATH="/path/to/MuJoCo.app/Contents/MacOS/mujoco_plugin"
#
# see the following page for details:  https://github.com/Farama-Foundation/Gymnasium/issues/749

moviepy = '~=1.0'
scikit-learn = '~=1.3'
pandas = '~=2.1'
patsy = '~=0.5'
pyqtgraph = '~=0.13'
tabulate = '~=0.9'
jupyterlab = '~=4.0'
ipython = '~=8.17'
jax = { version = '~=0.4', extras = ['cpu'] }

# can't get Qt6 to compile on raspberry pi. exclude this architecture.
PyQt6 = { version = '~=6.6', markers = 'platform_machine != "aarch64"' }

[tool.poetry.group.dev.dependencies]
pytest = '~=7.4'
pytest-cov = '~=4.1'
pytest-xdist = '~=3.4'
flake8 = '~=6.1'
flake8-annotations = '~=3.0'
flake8-docstrings = '~=1.7'
flake8-rst-docstrings = '~=0.3'
mypy = '~=1.7'
xvfbwrapper = '~=0.2'
coveralls = '~=3.3'
bump2version = '~=1.0'

[tool.poetry.scripts]
rlai = 'rlai.runners.top_level:run'
