[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-dir = {'' = 'src'}

[project]
name = 'rlai'
version = '1.1.0.dev0'
description = 'Reinforcement Learning:  An Introduction'
authors = [
    {name = 'Matthew Gerber', email = 'gerber.matthew@gmail.com'}
]
readme = 'README.md'
requires-python = '~=3.9'
dependencies = [
    'scipy~=1.11',
    'matplotlib~=3.8',
    'numpy~=1.26',
    'gym==0.24.1',
    'gym[box2d]==0.24.1',
    'scikit-learn~=1.3',
    'pandas~=2.1',
    'patsy~=0.5',
    'pyqtgraph~=0.13',
    'PyQt6~=6.6',
    'tabulate~=0.9',
    'mujoco-py==2.1.2.14',
    'mujoco==2.2.0',
    'jupyterlab~=4.0',
    'ipython~=8.17',

    # we compile jaxlib from source on aarch64 (e.g., for raspberry pi), so don't specify jax[cpu] here.
    'jax~=0.4; sys_platform=="linux-aarch64"',

    # otherwise, try to install cpu-only support.
    'jax[cpu]~=0.4; sys_platform!="linux-aarch64"'
]

[project.optional-dependencies]
dev = [
    'pytest~=7.4',
    'pytest-cov~=4.1',
    'pytest-xdist~=3.4',
    'flake8~=6.1',
    'flake8-annotations~=3.0',
    'flake8-docstrings~=1.7',
    'flake8-rst-docstrings~=0.3',
    'mypy~=1.7',
    'xvfbwrapper~=0.2',
    'coveralls~=3.3',
    'bump2version~=1.0'
]

[project.urls]
repository = 'https://github.com/MatthewGerber/rlai'
homepage = 'https://matthewgerber.github.io/rlai'

[project.scripts]
rlai = 'rlai.runners.top_level:run'
